language: node_js

node_js:
  - 8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - make test

dist: trusty

sudo: required

addons:
  chrome: stable
